
services:
  yt-dlp-api:
    build: .
    container_name: yt-dlp-api
    restart: unless-stopped
    environment:
      DOWNLOADS_DIR: /downloads
      MAX_FILESIZE: 50M
      VIDEO_TTL_SECONDS: 300
      PORT: 3000
      BIND_ADDR: 0.0.0.0
    networks:
      - yt-dlp

networks:
  yt-dlp:
    driver: bridge

